# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       meegotouchcp-connman

# >> macros
# << macros

Summary:    MeegoTouchControlPanel wifi Plugin
Version:    0.2.4
Release:    1
Group:      System/GUI/Other
License:    Apache License
URL:        https://github.com/nemomobile/meegotouchcp-connman
Source0:    %{name}-%{version}.tar.bz2
Source100:  meegotouchcp-connman.yaml
Requires:   connman-qt-declarative >= 0.2.2
BuildRequires:  qt-qmake
BuildRequires:  qt4-default
Obsoletes:   meegotouchcp-connman-branding-upsteam < 0.2.0
Obsoletes:   meegotouchcp-connman-qt < 0.2.0

%description
This is a plugin for meegotouch-controlpanel that does wifi



%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake 

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake_install

# >> install post
# << install post


%files
%defattr(-,root,root,-)
%{_libdir}/duicontrolpanel/meegotouchcp-wifi.desktop
%{_datadir}/duicontrolpanel/wifi/mainpage.qml
%{_datadir}/duicontrolpanel/wifi/NotificationBanner.qml
%{_datadir}/duicontrolpanel/wifi/SettingsSheet.qml
%{_libdir}/qt4/imports/Connman/js/mustache.js
# >> files
# << files
